//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiEIS.Entities
{
    using System;
    
    public enum InvoiceStatus : int
    {
        Entered = 1,
        WaitingOnApproval = 2,
        Approved = 3
    }
}
