//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiEIS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int Id { get; set; }
        public string LookupCode { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int PaymentMethod { get; set; }
        public string FileUrl { get; set; }
        public decimal SubTotal { get; set; }
        public decimal VATRate { get; set; }
        public decimal VATAmount { get; set; }
        public string Note { get; set; }
        public decimal Total { get; set; }
        public string AmountInWords { get; set; }
        public bool PaymentStatus { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        public string Enterprise { get; set; }
        public string Address { get; set; }
        public string TaxNo { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BankAccountNumber { get; set; }
        public string Bank { get; set; }
        public int TemplateId { get; set; }
        public string StaffId { get; set; }
        public string CustomerId { get; set; }
        public string CodeGuid { get; set; }
        public string FileUrl2 { get; set; }
        public string FileUrl3 { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
