//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiEIS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProformaInvoice()
        {
            this.ProformaInvoiceItems = new HashSet<ProformaInvoiceItem>();
        }
    
        public int Id { get; set; }
        public string LookupCode { get; set; }
        public System.DateTime Date { get; set; }
        public string FileUrl { get; set; }
        public System.DateTime PaymentDeadline { get; set; }
        public int Status { get; set; }
        public decimal SubTotal { get; set; }
        public decimal VATAmount { get; set; }
        public decimal TotalNoLiabilities { get; set; }
        public decimal Total { get; set; }
        public string StaffId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> Liabilities { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaInvoiceItem> ProformaInvoiceItems { get; set; }
    }
}
